"""All user-facing message strings centralized in one place."""

CANCELLED = "❌Download Cancelled"
CANCELLED_FA = "❌ دانلود لغو شد."
DL_FAILED = "❌ Download Failed"
DL_DONE = "Download has been finished."
RATE_LIMITED = "⏳ سرعت بیش از حد! {window} ثانیه صبر کنید."
NO_ACTIVE_DL = "هیچ دانلود فعالی وجود ندارد"
CANCELLED_ACTIVE = "❌ دانلود در حال انجام لغو شد."
MAINTENANCE = "🛠 ربات در حال آپدیت شدن است بعدا تلاش کنید..."
UNSUPPORTED_LINK = "THIS LINK IS NOT SUPPORTED :)"
MAINTENANCE_INLINE = "🛠 ربات در حال تعمیر است"
NOT_JOINED_INLINE = "❌ ابتدا عضو کانالها شوید"
NOT_JOINED_ALERT = "هنوز عضو همه کانالها نشدید ❌"
DEFAULT_START_MESSAGE = "سلام! اینجا ربات نیکسو اسپاتیفای هست 🗽\n\nاز دکمه های زیر برای سرچ اسم خواننده، آلبوم یا آهنگ استفاده کن 👇"
