"""All user-facing message strings centralized in one place."""

CANCELLED = "❌ Download Cancelled"
DL_FAILED = "❌ Download Failed"
DL_DONE = "Download has been finished."
RATE_LIMITED = "⏳ سرعت بیش از حد! {window} ثانیه صبر کنید."
NO_ACTIVE_DL = "هیچ دانلود فعالی وجود ندارد"
MAINTENANCE = "🛠 ربات در حال آپدیت شدن است بعدا تلاش کنید..."
UNSUPPORTED_LINK = "THIS LINK IS NOT SUPPORTED :)"
MAINTENANCE_INLINE = "🛠 ربات در حال تعمیر است"
NOT_JOINED_INLINE = "❌ ابتدا در کانال ها عضو شوید"
DEFAULT_START_MESSAGE = "سلام! اینجا ربات نیکسو اسپاتیفای هست 🗽\n\nاز دکمه های زیر برای سرچ اسم خواننده، آلبوم یا آهنگ استفاده کن 👇"
ARTIST_PROFILE_CAPTION = "Name: {real_name}\nNickname: {stage_name}\nDate of Birth: {dob}"
ARTIST_DOB_UNKNOWN = "Unknown"
